build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armhf: ghcr.io/home-assistant/armhf-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  i386: ghcr.io/home-assistant/i386-base:latest
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Endurian"
  org.opencontainers.image.description: "Self-hosted fitness tracking application with PostgreSQL support"
  org.opencontainers.image.source: "https://github.com/MichalTorma/ha-endurain"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.documentation: "https://github.com/MichalTorma/ha-endurain/blob/main/README.md"
args:
  ENDURIAN_VERSION: "v0.14.0"
