name: "Endurain Fitness Tracker"
description: "Self-hosted fitness tracking application with PostgreSQL support"
version: "0.3.6"
slug: "endurain"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: manual
hassio_api: true
hassio_role: default
host_network: false
privileged: []
ingress: true
ingress_port: 8080
panel_icon: mdi:run
panel_title: "Endurain"
panel_admin: false
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Endurain web interface"
map:
  - config:rw
  - ssl:ro
  - share:rw
options:
  endurain_version: "v0.14.0"
  app_title: "Endurain Fitness Tracker"
  app_description: "Self-hosted fitness tracking application"
  app_version: "0.14.0"
  postgres_host: "localhost"
  postgres_port: 5432
  postgres_user: "endurain"
  postgres_password: ""
  postgres_db: "endurain"
  postgres_schema: "public"
  secret_key: ""
  fernet_key: ""
  endurain_host: "http://localhost:8080"
  timezone: "UTC"
  reverse_geo_provider: "nominatim"
  photon_api_host: "photon.komoot.io"
  photon_api_use_https: true
  nominatim_api_host: "nominatim.openstreetmap.org"
  nominatim_api_use_https: true
  geocodes_maps_api: "changeme"
  reverse_geo_rate_limit: 1
  access_token_expire_minutes: 15
  refresh_token_expire_days: 7
  jaeger_enabled: false
  jaeger_protocol: "http"
  jaeger_host: "jaeger"
  jaeger_port: 4317
  environment: "production"
  smtp_host: ""
  smtp_port: 587
  smtp_username: ""
  smtp_password: ""
  smtp_secure: true
  smtp_secure_type: "starttls"
  behind_proxy: false
  cors_origins: "*"
  cors_methods: "GET,POST,PUT,DELETE"
  cors_headers: "*"
  log_level: "info"
  debug: false
  workers: 1
  bind_host: "0.0.0.0"
  bind_port: 8080
  upload_folder: "/share/endurain/uploads"
  max_content_length: 16777216
schema:
  endurain_version: "str"
  app_title: "str"
  app_description: "str"
  app_version: "str"
  postgres_host: "str"
  postgres_port: "port"
  postgres_user: "str"
  postgres_password: "password"
  postgres_db: "str"
  postgres_schema: "str"
  secret_key: "password"
  fernet_key: "password"
  endurain_host: "str"
  timezone: "str"
  reverse_geo_provider: "list(nominatim|photon|geocode)"
  photon_api_host: "str"
  photon_api_use_https: "bool"
  nominatim_api_host: "str"
  nominatim_api_use_https: "bool"
  geocodes_maps_api: "str"
  reverse_geo_rate_limit: "int(1,)"
  access_token_expire_minutes: "int(1,)"
  refresh_token_expire_days: "int(1,)"
  jaeger_enabled: "bool"
  jaeger_protocol: "list(http|https)"
  jaeger_host: "str"
  jaeger_port: "port"
  environment: "list(production|development)"
  smtp_host: "str"
  smtp_port: "port"
  smtp_username: "str"
  smtp_password: "password"
  smtp_secure: "bool"
  smtp_secure_type: "list(starttls|ssl)"
  behind_proxy: "bool"
  cors_origins: "str"
  cors_methods: "str"
  cors_headers: "str"
  log_level: "list(debug|info|warning|error|critical)"
  debug: "bool"
  workers: "int(1,10)"
  bind_host: "str"
  bind_port: "port"
  upload_folder: "str"
  max_content_length: "int(1,)"
